version: '3'

services:
  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://shop:password@pg:5432/shop
    ports:
      - "5050:5000"
    volumes:
      - ./:/var/app/
    depends_on:
      - pg

  shop-prod:
    build:
      context: .
      dockerfile: docker-build/shop-prod/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://shop:password@pg:5432/shop
    ports:
      - "5080:5000"
    depends_on:
      - pg

  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  db-data:
